### ISSUE TITLE
Implement static generation and github hooks

### ISSUE THREAD

**Issue by doppioslash** [rust-gamedev/arewegameyet#12]
This requires cobalt-rs to support data files.

**Comment by doppioslash** [comment]
Turns out by automatic we'd get a lot of wrong info, because people don't keep their crates.io library entries up-to-date...

**Comment by viperscape** [comment]
Hi, do you have a separate repo containing any automation work for this yet? I had some ideas

**Comment by doppioslash** [comment]
No, I don't. Only researched how arewewebyet was doing it, and figuring out that cobalt lacks the data files feature.

**Comment by viperscape** [comment]
Hey, sorry been super busy but wanted to look at this again :) What do you mean by data files?

"Turns out by automating we'd get a lot of wrong info, because people don't keep their crates.io library entries up-to-date..."
I think even if the information was out of date, the crates.io info should be used to drive this if possible. You could have a list here that is appended to, specifying the registered crate name. The site could rebuild when PRd and pull data from crates.io if possible, then use something like handlbars templating to render the results (eg: https://github.com/sunng87/handlebars-rust/blob/master/examples/render_file/template.hbs)

Also, just saw this pop up on my radar: https://bitbucket.org/Alex_PK/strange/

**Comment by doppioslash** [comment]
The data files feature that they use from Jekyll 
https://jekyllrb.com/docs/datafiles/
https://github.com/bashyHQ/arewewebyet/tree/gh-pages/_data/pkgs

**Comment by doppioslash** [comment]
at a first look `strange` seems to have that feature

**Comment by viperscape** [comment]
I have forked and started proceeding on the autogenerating code

https://github.com/viperscape/arewegameyet

so far it parses crates based on a list, next up it will render the Crate objects into basic html snippets (probably using [mustache](https://github.com/nickel-org/rust-mustache))

**Comment by doppioslash** [comment]
Cool!

**Comment by viperscape** [comment]
Given this generic crate view: https://github.com/viperscape/arewegameyet/blob/master/views/crates.html
and these crates: https://github.com/viperscape/arewegameyet/blob/master/config/categories.toml#L6
it can render this output: https://github.com/viperscape/arewegameyet/blob/master/build/scripting.html

I think functionality wise, this is in pretty good shape, I am only taking in these crate attributes from crates.io:
```rust
#[derive(Debug,RustcEncodable)]
pub struct Crate {
    name: String,
    version: String,
    description: String,
    license: String,
    repository: String
}
```
So if we want more, we'll have to add them in to the parser.

I moved your original site files into static for now, and the output generated goes in to Build. I think it will make more sense to have everything in a subdir called ```site```. That will take some organization and updating of the static assets. It also looks like the css should be put in to a css file. Take a look and maybe tinker, let me know what you think!

**Comment by GloverDonovan** [comment]
Bumping this. I'd like to see #7 fixed as well!

@viperscape I looked through your fork and it seems much better than how things are handled now. Is there any update on whether or not this change is welcome?

**Comment by viperscape** [comment]
@GloverDonovan Thanks! No response, my guess is this is low on @doppioslash totem pole 😄 Like I said, it would take some rework on the static assets side, but shouldn't be too bad really.

**Comment by piedoom** [comment]
Hi!  Would you consider using Gutenberg?  Its written in Rust and has support for data files.  I've been using it for quite some time and love it.  https://github.com/Keats/gutenberg/

Here is the PR in question https://github.com/Keats/gutenberg/issues/476  I believe it will be in the next release which should be dropping soon.  (Note that it is changing the name to Zola due to wordpress seo stuff).  I would be happy to assist.

**Comment by doppioslash** [comment]
Hey @piedoom, yeah I would consider that.

**Comment by erlend-sh** [comment]
#128 solves this. I've started an issue to discuss further enhancements in #151.

**Comment by mbillingr** [comment]
The order in which crates are listed on the category pages seems quite arbitrary. They appear in the same order they are listed in the data file. It would be nice if there was *some* order...

Does Zola support automatic sorting of items by name or meta data (such as number of downloads)?

**Comment by ozkriff** [comment]
This issue can be closed now, right?
