### ISSUE TITLE
Add game engine: godot-rust

### ISSUE THREAD

**Issue by kubo39** [rust-gamedev/arewegameyet#191]
Rust bindings to the Godot game engine.

crate: https://crates.io/crates/gdnative
github: https://github.com/GodotNativeTools/godot-rust

**Comment by Waridley** [comment]
Should this replace the "godot" crate entry? That crate seems to be completely empty, like someone took it to reserve the name or something. I found the gdnative crate after looking into Godot itself and reading about GDNative, which made me think if you could write C code, there must be a way to write bindings for Rust. Turns out there was, and someone already started it, it just was impossible to find without knowing I was looking for "gdnative".

**Comment by Waridley** [comment]
Nvm, just saw the PR for it!
