### ISSUE TITLE
Sort crates by downloads

### ISSUE THREAD

**Issue by PonasKovas** [rust-gamedev/arewegameyet#330]

**Comment by 17cupsofcoffee** [comment]
This has been discussed previously in https://github.com/rust-gamedev/arewegameyet/issues/157. The main issues with sorting by downloads are:

* We'd only be able to do it for items that are hosted on Crates.io.
* It disproportionately favours older and low-level crates. For example, Piston is the most downloaded game engine, because it was one of the first released, but it's not the most widely used today.
