### ISSUE TITLE
Experiment with a special "archive" category

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/arewegameyet#485]
See https://github.com/rust-gamedev/arewegameyet/pull/483

I'll try to make the initial prototype in a week or so (i'm terrible at time estimations though).

Related to https://github.com/rust-gamedev/arewegameyet/issues/95
Related to https://github.com/rust-gamedev/arewegameyet/issues/320

**Comment by ozkriff** [comment]
> I'm against removing even more stuff from the database, I'd much prefer the archived category to be implemented - https://github.com/rust-gamedev/arewegameyet/issues/485 - though I wasn't able to really work on this yet and won't be in the next couple of weeks. If anyone feels that the need to clean up AWGY is urgent, please feel free to propose PRs that introduce the "archived" category.

So yeah, if anyone wants to work on this now, feel free to propose PRs.

**Comment by 17cupsofcoffee** [comment]
I finally have a bit of free time now, so I had a go at mocking something up for an 'archive' section:

![image](https://github.com/rust-gamedev/arewegameyet/assets/784533/c0754ea3-b957-4d2f-976b-1685e179ad2f)

I chose to add it to the existing category pages rather than creating new ones for the sake of simplicity.

Couple of other tweaks I considered:

* Rather than having a seperate section, we could just grey them out and sort to the bottom of the list, but not sure whether that would make it clear enough.
    * I could also grey/red them out even with the layout shown above, just to make them a little more visually distinct.
* It could be worth us disabling Crates.io/GitHub data fetching for archived crates, to speed up the build a little.
* Not sure if the bed icon makes sense, but I couldn't find a more fitting one 😆 

Any thoughts on this?

**Comment by ozkriff** [comment]
@17cupsofcoffee (sorry for the late reply!)

> I chose to add it to the existing category pages rather than creating new ones for the sake of simplicity.

yeah, it sounds great to me! and I agree that it's worth graying them out anyway too.

> It could be worth us disabling Crates.io/GitHub data fetching for archived crates, to speed up the build a little.

most of the libraries don't have a description in our data.toml so if we disable data fetching only a name would left. i'd prefer to keep data fetching for them, at least for now.

> Not sure if the bed icon makes sense, but I couldn't find a more fitting one 😆

I agree that it's probably not perfect but I too can't find a better icon quickly so let's keep the bed icon for now - we can always change it later.

So please open a PR! :pray:

**Comment by 17cupsofcoffee** [comment]
Added in #546.
